# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\admin_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_admin_win(object):
    def setupUi(self, Dialog_admin_win):
        Dialog_admin_win.setObjectName("Dialog_admin_win")
        Dialog_admin_win.resize(1555, 549)
        Dialog_admin_win.setMinimumSize(QtCore.QSize(1555, 0))
        self.tableWidget_app_output = QtWidgets.QTableWidget(Dialog_admin_win)
        self.tableWidget_app_output.setGeometry(QtCore.QRect(10, 180, 1521, 361))
        self.tableWidget_app_output.setMaximumSize(QtCore.QSize(16777215, 125655))
        self.tableWidget_app_output.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget_app_output.setObjectName("tableWidget_app_output")
        self.tableWidget_app_output.setColumnCount(0)
        self.tableWidget_app_output.setRowCount(0)
        self.pushButton_show_masters = QtWidgets.QPushButton(Dialog_admin_win)
        self.pushButton_show_masters.setGeometry(QtCore.QRect(20, 30, 121, 23))
        self.pushButton_show_masters.setObjectName("pushButton_show_masters")
        self.pushButton_show_masters_messages = QtWidgets.QPushButton(Dialog_admin_win)
        self.pushButton_show_masters_messages.setGeometry(QtCore.QRect(160, 30, 141, 23))
        self.pushButton_show_masters_messages.setObjectName("pushButton_show_masters_messages")
        self.pushButton_exit = QtWidgets.QPushButton(Dialog_admin_win)
        self.pushButton_exit.setGeometry(QtCore.QRect(460, 30, 41, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_orders_history = QtWidgets.QPushButton(Dialog_admin_win)
        self.pushButton_orders_history.setGeometry(QtCore.QRect(310, 30, 141, 23))
        self.pushButton_orders_history.setObjectName("pushButton_orders_history")

        self.retranslateUi(Dialog_admin_win)
        QtCore.QMetaObject.connectSlotsByName(Dialog_admin_win)

    def retranslateUi(self, Dialog_admin_win):
        _translate = QtCore.QCoreApplication.translate
        Dialog_admin_win.setWindowTitle(_translate("Dialog_admin_win", "Панель управления"))
        self.pushButton_show_masters.setText(_translate("Dialog_admin_win", "Список мастеров"))
        self.pushButton_show_masters_messages.setText(_translate("Dialog_admin_win", "Сообщения"))
        self.pushButton_exit.setText(_translate("Dialog_admin_win", "<--"))
        self.pushButton_orders_history.setText(_translate("Dialog_admin_win", "История заказов"))
