# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Autorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Autorization_win(object):
    def setupUi(self, Autorization_win):
        Autorization_win.setObjectName("Autorization_win")
        Autorization_win.resize(410, 500)
        Autorization_win.setMaximumSize(QtCore.QSize(410, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\QtDesign\\../task and images/Мастер пол.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Autorization_win.setWindowIcon(icon)
        Autorization_win.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: 2499ff;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        Autorization_win.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Autorization_win.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Autorization_win)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 140, 202, 179))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_login_autoriz = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_login_autoriz.setObjectName("lineEdit_login_autoriz")
        self.verticalLayout.addWidget(self.lineEdit_login_autoriz)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_password_autoriz = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_password_autoriz.setObjectName("lineEdit_password_autoriz")
        self.verticalLayout.addWidget(self.lineEdit_password_autoriz)
        self.pushButton_autoriz = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_autoriz.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_autoriz.setStyleSheet("QPushButton \n"
"{     \n"
"background-color:rgb(32, 170, 255);  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */    \n"
"border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_autoriz.setObjectName("pushButton_autoriz")
        self.verticalLayout.addWidget(self.pushButton_autoriz)
        self.pushButton_registration_f_autor = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_registration_f_autor.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_registration_f_autor.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: rgb(32, 170, 255);  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_registration_f_autor.setObjectName("pushButton_registration_f_autor")
        self.verticalLayout.addWidget(self.pushButton_registration_f_autor)
        Autorization_win.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Autorization_win)
        self.statusbar.setObjectName("statusbar")
        Autorization_win.setStatusBar(self.statusbar)

        self.retranslateUi(Autorization_win)
        QtCore.QMetaObject.connectSlotsByName(Autorization_win)

    def retranslateUi(self, Autorization_win):
        _translate = QtCore.QCoreApplication.translate
        Autorization_win.setWindowTitle(_translate("Autorization_win", "Авторизация"))
        self.label_2.setText(_translate("Autorization_win", "Логин"))
        self.label_5.setText(_translate("Autorization_win", "Пароль"))
        self.pushButton_autoriz.setText(_translate("Autorization_win", "Войти"))
        self.pushButton_registration_f_autor.setText(_translate("Autorization_win", "Регистрация"))
