# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\client_edit_application.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(686, 578)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(20, 290, 641, 281))
        self.tableView.setObjectName("tableView")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 251, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_org_tech_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_org_tech_type.setObjectName("comboBox_org_tech_type")
        self.verticalLayout.addWidget(self.comboBox_org_tech_type)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_client_fio = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_client_fio.setObjectName("lineEdit_client_fio")
        self.verticalLayout.addWidget(self.lineEdit_client_fio)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_client_telephone = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_client_telephone.setObjectName("lineEdit_client_telephone")
        self.verticalLayout.addWidget(self.lineEdit_client_telephone)
        self.pushButton_add_client_info = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_add_client_info.setObjectName("pushButton_add_client_info")
        self.verticalLayout.addWidget(self.pushButton_add_client_info)
        self.pushButton_add_client_info_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_add_client_info_2.setObjectName("pushButton_add_client_info_2")
        self.verticalLayout.addWidget(self.pushButton_add_client_info_2)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(280, 10, 381, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Работа с заявками"))
        self.label.setText(_translate("Dialog", "Вид орг техники"))
        self.label_2.setText(_translate("Dialog", "ФИО"))
        self.label_3.setText(_translate("Dialog", "Телефон"))
        self.pushButton_add_client_info.setText(_translate("Dialog", "Отправить заявку"))
        self.pushButton_add_client_info_2.setText(_translate("Dialog", "Редактировать заявку"))
        self.label_4.setText(_translate("Dialog", "Описание проблемы"))
