# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\client_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_client_win(object):
    def setupUi(self, Dialog_client_win):
        Dialog_client_win.setObjectName("Dialog_client_win")
        Dialog_client_win.resize(676, 428)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_client_win)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 251, 273))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_org_tech_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_org_tech_type.setObjectName("comboBox_org_tech_type")
        self.verticalLayout.addWidget(self.comboBox_org_tech_type)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_client_fio = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_client_fio.setObjectName("lineEdit_client_fio")
        self.verticalLayout.addWidget(self.lineEdit_client_fio)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_model_type = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_model_type.setObjectName("lineEdit_model_type")
        self.verticalLayout.addWidget(self.lineEdit_model_type)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_client_telephone = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_client_telephone.setObjectName("lineEdit_client_telephone")
        self.verticalLayout.addWidget(self.lineEdit_client_telephone)
        self.pushButton_push_application = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_push_application.setObjectName("pushButton_push_application")
        self.verticalLayout.addWidget(self.pushButton_push_application)
        self.layoutWidget = QtWidgets.QWidget(Dialog_client_win)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 20, 381, 385))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.textEdit_problem_description = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_problem_description.setObjectName("textEdit_problem_description")
        self.verticalLayout_2.addWidget(self.textEdit_problem_description)
        self.pushButton_exit_3 = QtWidgets.QPushButton(Dialog_client_win)
        self.pushButton_exit_3.setGeometry(QtCore.QRect(10, 320, 41, 23))
        self.pushButton_exit_3.setObjectName("pushButton_exit_3")

        self.retranslateUi(Dialog_client_win)
        QtCore.QMetaObject.connectSlotsByName(Dialog_client_win)

    def retranslateUi(self, Dialog_client_win):
        _translate = QtCore.QCoreApplication.translate
        Dialog_client_win.setWindowTitle(_translate("Dialog_client_win", "Работа с заявками"))
        self.label.setText(_translate("Dialog_client_win", "Вид орг техники"))
        self.label_2.setText(_translate("Dialog_client_win", "ФИО"))
        self.label_5.setText(_translate("Dialog_client_win", "Модель техники"))
        self.label_3.setText(_translate("Dialog_client_win", "Телефон"))
        self.pushButton_push_application.setText(_translate("Dialog_client_win", "Отправить заявку"))
        self.label_4.setText(_translate("Dialog_client_win", "Описание проблемы"))
        self.pushButton_exit_3.setText(_translate("Dialog_client_win", "<--"))
