# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\components_inspection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_components_inspection(object):
    def setupUi(self, Dialog_components_inspection):
        Dialog_components_inspection.setObjectName("Dialog_components_inspection")
        Dialog_components_inspection.resize(900, 468)
        self.layoutWidget = QtWidgets.QWidget(Dialog_components_inspection)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 230, 211, 134))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox_output_components = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_output_components.setObjectName("comboBox_output_components")
        self.verticalLayout.addWidget(self.comboBox_output_components)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_quantity_insert = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_quantity_insert.setObjectName("lineEdit_quantity_insert")
        self.verticalLayout.addWidget(self.lineEdit_quantity_insert)
        self.pushButton_repairs_buy = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_repairs_buy.setObjectName("pushButton_repairs_buy")
        self.verticalLayout.addWidget(self.pushButton_repairs_buy)
        self.tableWidget_repairs_output = QtWidgets.QTableWidget(Dialog_components_inspection)
        self.tableWidget_repairs_output.setGeometry(QtCore.QRect(10, 10, 871, 201))
        self.tableWidget_repairs_output.setObjectName("tableWidget_repairs_output")
        self.tableWidget_repairs_output.setColumnCount(0)
        self.tableWidget_repairs_output.setRowCount(0)
        self.widget = QtWidgets.QWidget(Dialog_components_inspection)
        self.widget.setGeometry(QtCore.QRect(230, 230, 191, 70))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_insert_component = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_insert_component.setObjectName("lineEdit_insert_component")
        self.verticalLayout_2.addWidget(self.lineEdit_insert_component)
        self.pushButton_add_component = QtWidgets.QPushButton(self.widget)
        self.pushButton_add_component.setObjectName("pushButton_add_component")
        self.verticalLayout_2.addWidget(self.pushButton_add_component)

        self.retranslateUi(Dialog_components_inspection)
        QtCore.QMetaObject.connectSlotsByName(Dialog_components_inspection)

    def retranslateUi(self, Dialog_components_inspection):
        _translate = QtCore.QCoreApplication.translate
        Dialog_components_inspection.setWindowTitle(_translate("Dialog_components_inspection", "Информация о компонентах"))
        self.label_2.setText(_translate("Dialog_components_inspection", "Выберите компонент для покупки"))
        self.label.setText(_translate("Dialog_components_inspection", "Введите количество"))
        self.pushButton_repairs_buy.setText(_translate("Dialog_components_inspection", "Заказать детали"))
        self.label_3.setText(_translate("Dialog_components_inspection", "Добавить компонент"))
        self.pushButton_add_component.setText(_translate("Dialog_components_inspection", "Добавить"))
