# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\master_messages.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_messages_admin(object):
    def setupUi(self, Dialog_messages_admin):
        Dialog_messages_admin.setObjectName("Dialog_messages_admin")
        Dialog_messages_admin.resize(1015, 511)
        self.tableWidget_output_messages = QtWidgets.QTableWidget(Dialog_messages_admin)
        self.tableWidget_output_messages.setGeometry(QtCore.QRect(10, 10, 991, 491))
        self.tableWidget_output_messages.setObjectName("tableWidget_output_messages")
        self.tableWidget_output_messages.setColumnCount(0)
        self.tableWidget_output_messages.setRowCount(0)

        self.retranslateUi(Dialog_messages_admin)
        QtCore.QMetaObject.connectSlotsByName(Dialog_messages_admin)

    def retranslateUi(self, Dialog_messages_admin):
        _translate = QtCore.QCoreApplication.translate
        Dialog_messages_admin.setWindowTitle(_translate("Dialog_messages_admin", "Сообщения "))
