# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\master_order_work.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_order_work(object):
    def setupUi(self, Dialog_order_work):
        Dialog_order_work.setObjectName("Dialog_order_work")
        Dialog_order_work.resize(874, 490)
        self.tableWidget_orders_output = QtWidgets.QTableWidget(Dialog_order_work)
        self.tableWidget_orders_output.setGeometry(QtCore.QRect(30, 10, 781, 261))
        self.tableWidget_orders_output.setObjectName("tableWidget_orders_output")
        self.tableWidget_orders_output.setColumnCount(0)
        self.tableWidget_orders_output.setRowCount(0)
        self.widget = QtWidgets.QWidget(Dialog_order_work)
        self.widget.setGeometry(QtCore.QRect(20, 280, 261, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox_order_id = QtWidgets.QComboBox(self.widget)
        self.comboBox_order_id.setObjectName("comboBox_order_id")
        self.verticalLayout.addWidget(self.comboBox_order_id)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_components_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_components_name.setObjectName("lineEdit_components_name")
        self.verticalLayout.addWidget(self.lineEdit_components_name)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_components_quantity = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_components_quantity.setObjectName("lineEdit_components_quantity")
        self.verticalLayout.addWidget(self.lineEdit_components_quantity)
        self.pushButton_push_info_in = QtWidgets.QPushButton(self.widget)
        self.pushButton_push_info_in.setObjectName("pushButton_push_info_in")
        self.verticalLayout.addWidget(self.pushButton_push_info_in)

        self.retranslateUi(Dialog_order_work)
        QtCore.QMetaObject.connectSlotsByName(Dialog_order_work)

    def retranslateUi(self, Dialog_order_work):
        _translate = QtCore.QCoreApplication.translate
        Dialog_order_work.setWindowTitle(_translate("Dialog_order_work", "Внесение изменений в заявку"))
        self.label_3.setText(_translate("Dialog_order_work", "Выбор заявки"))
        self.label.setText(_translate("Dialog_order_work", "Наименование компонента"))
        self.label_2.setText(_translate("Dialog_order_work", "Использованное кол-во"))
        self.pushButton_push_info_in.setText(_translate("Dialog_order_work", "Внести изменения"))
