# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\master_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_master_win(object):
    def setupUi(self, Dialog_master_win):
        Dialog_master_win.setObjectName("Dialog_master_win")
        Dialog_master_win.resize(900, 398)
        self.pushButton_order_work = QtWidgets.QPushButton(Dialog_master_win)
        self.pushButton_order_work.setGeometry(QtCore.QRect(20, 20, 121, 28))
        self.pushButton_order_work.setObjectName("pushButton_order_work")
        self.textEdit_master_message = QtWidgets.QTextEdit(Dialog_master_win)
        self.textEdit_master_message.setGeometry(QtCore.QRect(20, 60, 497, 280))
        self.textEdit_master_message.setMinimumSize(QtCore.QSize(280, 280))
        self.textEdit_master_message.setObjectName("textEdit_master_message")
        self.pushButton_repairs_watch = QtWidgets.QPushButton(Dialog_master_win)
        self.pushButton_repairs_watch.setGeometry(QtCore.QRect(150, 20, 121, 28))
        self.pushButton_repairs_watch.setObjectName("pushButton_repairs_watch")
        self.pushButton_push_message = QtWidgets.QPushButton(Dialog_master_win)
        self.pushButton_push_message.setGeometry(QtCore.QRect(180, 360, 151, 23))
        self.pushButton_push_message.setObjectName("pushButton_push_message")
        self.pushButton_exit_2 = QtWidgets.QPushButton(Dialog_master_win)
        self.pushButton_exit_2.setGeometry(QtCore.QRect(830, 20, 41, 23))
        self.pushButton_exit_2.setObjectName("pushButton_exit_2")

        self.retranslateUi(Dialog_master_win)
        QtCore.QMetaObject.connectSlotsByName(Dialog_master_win)

    def retranslateUi(self, Dialog_master_win):
        _translate = QtCore.QCoreApplication.translate
        Dialog_master_win.setWindowTitle(_translate("Dialog_master_win", "Окно мастера"))
        self.pushButton_order_work.setText(_translate("Dialog_master_win", "Заполнить отчет"))
        self.pushButton_repairs_watch.setText(_translate("Dialog_master_win", "Просмотр деталей"))
        self.pushButton_push_message.setText(_translate("Dialog_master_win", "Оставить сообщение"))
        self.pushButton_exit_2.setText(_translate("Dialog_master_win", "<--"))
