# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\orders_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_orders_history(object):
    def setupUi(self, Dialog_orders_history):
        Dialog_orders_history.setObjectName("Dialog_orders_history")
        Dialog_orders_history.resize(789, 727)
        self.tableWidge_orders_history = QtWidgets.QTableWidget(Dialog_orders_history)
        self.tableWidge_orders_history.setGeometry(QtCore.QRect(20, 10, 751, 691))
        self.tableWidge_orders_history.setObjectName("tableWidge_orders_history")
        self.tableWidge_orders_history.setColumnCount(0)
        self.tableWidge_orders_history.setRowCount(0)

        self.retranslateUi(Dialog_orders_history)
        QtCore.QMetaObject.connectSlotsByName(Dialog_orders_history)

    def retranslateUi(self, Dialog_orders_history):
        _translate = QtCore.QCoreApplication.translate
        Dialog_orders_history.setWindowTitle(_translate("Dialog_orders_history", "История заказов"))
