# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtDesign\Registration_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration_win(object):
    def setupUi(self, Registration_win):
        Registration_win.setObjectName("Registration_win")
        Registration_win.resize(413, 501)
        Registration_win.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: #67BA80;  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */    \n"
"border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Registration_win)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 70, 202, 335))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_registr = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_registr.setObjectName("comboBox_registr")
        self.verticalLayout.addWidget(self.comboBox_registr)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_login_registr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_login_registr.setObjectName("lineEdit_login_registr")
        self.verticalLayout.addWidget(self.lineEdit_login_registr)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_password_registr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_password_registr.setObjectName("lineEdit_password_registr")
        self.verticalLayout.addWidget(self.lineEdit_password_registr)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_fio_registr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_fio_registr.setObjectName("lineEdit_fio_registr")
        self.verticalLayout.addWidget(self.lineEdit_fio_registr)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_telephone_registr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_telephone_registr.setObjectName("lineEdit_telephone_registr")
        self.verticalLayout.addWidget(self.lineEdit_telephone_registr)
        self.pushButton_registr_user = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_registr_user.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_registr_user.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: rgb(32, 170, 255);  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */    \n"
"border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_registr_user.setObjectName("pushButton_registr_user")
        self.verticalLayout.addWidget(self.pushButton_registr_user)
        self.pushButton_registration_f_autor = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_registration_f_autor.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_registration_f_autor.setStyleSheet("QPushButton \n"
"{     \n"
"background-color: rgb(32, 170, 255);  /* Цвет фона кнопки */    \n"
"color: white;  /* Цвет текста */     border-radius: 5px;  /* Скругленные углы */ \n"
"}")
        self.pushButton_registration_f_autor.setObjectName("pushButton_registration_f_autor")
        self.verticalLayout.addWidget(self.pushButton_registration_f_autor)

        self.retranslateUi(Registration_win)
        QtCore.QMetaObject.connectSlotsByName(Registration_win)

    def retranslateUi(self, Registration_win):
        _translate = QtCore.QCoreApplication.translate
        Registration_win.setWindowTitle(_translate("Registration_win", "Регистрация"))
        self.label.setText(_translate("Registration_win", "Роль"))
        self.label_2.setText(_translate("Registration_win", "Логин"))
        self.label_5.setText(_translate("Registration_win", "Пароль"))
        self.label_4.setText(_translate("Registration_win", "ФИО"))
        self.label_3.setText(_translate("Registration_win", "Телефон"))
        self.pushButton_registr_user.setText(_translate("Registration_win", "Создать учетную запись"))
        self.pushButton_registration_f_autor.setText(_translate("Registration_win", "Авторизация"))
